### ISSUE TITLE
ADD PHOTOS

### ISSUE THREAD

**Issue by saponciou** [wisp-forest/docs#4]
please i beg. Add photos to the docs

**Comment by gliscowo** [comment]
Could you maybe elaborate what exactly you're thinking of here? As far as we're concerned, all areas of the docs that can majorly benefit from pictures already have them - so where do you feel they're missing?

**Comment by saponciou** [comment]
Sorry for my bad question before.
I just want to say, that for example, the isometric renders page in the docs dont have any example such a image of how it would look or something like that. Also in owo's page dont have any type of example or image for clarify how an implementation will look like.

**Comment by gliscowo** [comment]
I'm still quite unsure what you mean precisely. With Isometric Renders for example, there isn't much to show - the renders simply look like the objects from the game they represent after all. 

It'd likely help to make your point more clear to us if you could provide some specific examples of where exactly in the docs you think some extra pictures could enhance the experience - and ideally also what you'd like them to depict

**Comment by saponciou** [comment]
For example. At https://docs.wispforest.io/owo/registration/ I think there could be some images that graphically represent what the code block does. Something like on the https://docs.wispforest.io/owo/ui/getting-started/ page.

**Comment by gliscowo** [comment]
Now this has me puzzled - how would you graphically represent registration? I genuinely can't think of any meaningful way to visualize that. Do you have anything in mind?

Furthermore, I also don't quite see how visualizing registration would help - even if there was a good way to do it. It's inherently not a visual process and trivial to understand as is already

**Comment by gliscowo** [comment]
As this issue does not appear to lead to any useful place, I'll be closing it for the time being. If you do end up having some concrete example of where more images would be useful and what they would show, feel free to re-open it and bring it up with us again

Cheers
